### ISSUE TITLE
InfraValidator got "RBAC: access denied" on Kubeflow 

### ISSUE THREAD

**Issue by wyljpn** [tensorflow/tfx#3893]
**System information**

- Have I specified the code to reproduce the issue (Yes, No): Yes.
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows), 
  Interactive Notebook, Google Cloud, etc): Minikube v1.19.0, kubeflow v1.3, K8s Client version v1.21.1, Server v1.20.2
- TensorFlow version: 2.4.1
- TFX Version: 0.28.0
- Python version: 3.7.10

**Describe the current behavior**
When running Infravalidator on Kubeflow, it will get "RBAC: access denied".
![image](https://user-images.githubusercontent.com/37242439/120979911-014e9c80-c7b1-11eb-8645-6c2fb5684e65.png)

**Describe the expected behavior**
InfraValidator, "components-20210601-zjwzh-3877683498",  on Kubeflow create a pod called "tfx-infraval-modelserver-*****" under the same namespace. And a model trained by a Trainer component be loaded by tf-serving on the pod. Then InfraValidator sends gRPC requests to the pod and gets responses from the pod, like the followed picture.

![image](https://user-images.githubusercontent.com/37242439/120980068-322ed180-c7b1-11eb-961e-2d51643cbf84.png)

**Standalone code to reproduce the issue**
No, but I have run the same pipeline on my PC several times, and also run it on another PC, it got the same errors.

**Other info / logs**

I have got into the "tfx-infraval-modelserver-*****" pod created by InfraValidator and noticed that the model was loaded by tf serving and 8500 port was licensed. 

![image](https://user-images.githubusercontent.com/37242439/120982427-abc7bf00-c7b3-11eb-8684-319167d6b9b8.png)

![image](https://user-images.githubusercontent.com/37242439/120982513-c1d57f80-c7b3-11eb-8b8e-9d59edbf306d.png)

![image](https://user-images.githubusercontent.com/37242439/120982330-918de100-c7b3-11eb-9985-57a4a6f735e6.png)

So I think the issue is that something causes the "components-20210601-zjwzh-3877683498" pod can't communicate with "tfx-infraval-modelserver-*****" pod.

**Comment by wyljpn** [comment]
I had found a related issue on Kubeflow Repo https://github.com/kubeflow/pipelines/issues/4440 
and got some advice from @DavidSpek.
Now I have two solutions to solve this issue, but both of them have some potential issues. 
1: Apply an AuthorizationPolicy. 
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-all
  namespace: kubeflow-user-example-com
spec:
 rules:
 - {}
```
By applying the AuthorizationPolicy, InfraValidator successfully ran. 
https://istio.io/latest/docs/reference/config/security/authorization-policy/

However, there are some potential issues that DavidSpek told me.
> You should not apply this AuthorizationPolicy, as it allows all traffic from anywhere to access your namespace. Which would also mean others can access your notebook instances, for example.
I do want to allow all communication within the namespace, so I tried to add a selector for the same namespace.
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-all-from-same-ns
  namespace: kubeflow-user-example-com
spec:
  action: ALLOW
  rules:
  - from:
     - source:
        namespaces: ["kubeflow-user-example-com"]
``` 
But it didn't work, It got "RBAC: access denied" again.

--------------------------

2: Disable Sidecar for the namespace using a kubectl command.

> Another option would be to disable Istio injection for the TFX pods by adding the sidecar.istio.io/inject: "false" label to the pods. 


Since the first solution cannot solve the issue perfectly, I have tried another solution.

On the Istio website, I found I can disable Sidecar by adding a label for the namespace. 
https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/
```
$ kubectl label namespace kubeflow-user-example-com istio-injection=disabled --overwrite
```
It did work, but it disabled all the pods under the namespace, it may also have some potential issues?
So I wanted to disable the Sidecar for the two related pods by running the commands below. 
```
$ kubectl label pods 20210601-zjwzh-3877683498 -n kubeflow-user-example-com sidecar.istio.io/inject="false"  --overwrite
$ k label pod tfx-infraval-modelserver-72n7m  -n kubeflow-user-example-com sidecar.istio.io/inject="false"  --overwrite
```
It turned out that the InfraValidator pod got "RBAC: access denied" again.

----------------

Actually, I have tried to apply a Sidecar, but it didn't work at all.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: kubeflow-user-example-com
spec:
  egress:
  - hosts:
    - "./*"
    - "kubeflow-user-example-com/*"
```

----------------

Does anyone meet these situations before?

**Comment by ConverJens** [comment]
@wyljpn I have already supplied a PR for this issue in TFX which has been merged since 0.30.0. Basically you only need to set an annotation on your serving pod which can be configured in the InfraValidator. See https://github.com/kubeflow/pipelines/issues/5164 and https://github.com/tensorflow/tfx/pull/3541

**Comment by arghyaganguly** [comment]
@wyljpn , please confirm whether @ConverJens comment was helpful to you.Thanks.

**Comment by wyljpn** [comment]
@arghyaganguly @ConverJens Thank you for your response.

Based on the source code (https://github.com/tensorflow/tfx/blob/master/tfx/proto/infra_validator.proto) and description (need to set an annotation on your serving pod which can be configured in the InfraValidator), I wrote down the code below. I not sure whether it is right, since I didn't saw examples. 

And until last week, I was only using 0.28. When I tried to use 0.30.0 today, Transform component got errors, so I couldn't immediately check whether the code below is working or not. 

``` Python
    # InfraValidator
    infra_validator = InfraValidator(
        model=trainer.outputs['model'],
        examples=example_gen.outputs['examples'],
        serving_spec=ServingSpec(
            tensorflow_serving=TensorFlowServing(tags=['latest']),
            kubernetes=KubernetesConfig(serving_pod_overrides=PodOverrides(annotations=dict({"sidecar.istio.io/inject": "false"})))
        )
    )
```

**Comment by DavidSpek** [comment]
@wyljpn The serving pods should have Istio injection enabled as far as I know. However, there are some fixes for the profile controller that have since been merged that set the required authorization policy.

**Comment by ConverJens** [comment]
@wyljpn That looks right and should work.

@DavidSpek This is a temporary serving pod spwaned by a pipeline component and hence, it should not have an istio side-car just like any other pipeline component. You can verify that pipeline pod has this annotation (which the IV serving pod lacks by default) by looking at the pod tab in KFP UI .

**Comment by wyljpn** [comment]
@ConverJens @DavidSpek Thank you for your check and comment.
After I deal with the errors about the Transform component, I will run the pipeline on Kubeflow to check whether the code works.

**Comment by wyljpn** [comment]
@ConverJens 
If pipeline component pods don't have sidecars, why it works when we set 
```
$ kubectl label namespace kubeflow-user-example-com istio-injection=disabled --overwrite
```
or 
```Python
    # InfraValidator
    infra_validator = InfraValidator(
        model=trainer.outputs['model'],
        examples=example_gen.outputs['examples'],
        serving_spec=ServingSpec(
            tensorflow_serving=TensorFlowServing(tags=['latest']),
            kubernetes=KubernetesConfig(serving_pod_overrides=PodOverrides(annotations={"sidecar.istio.io/inject": "false"}))
        )
    )
```

-------------------------

I am confused because there are descriptions on the istio website (https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/) 
> The following sections describe two ways of injecting the Istio sidecar into a pod: **enabling automatic Istio sidecar injection in the pod’s namespace**, or by manually using the istioctl command.
> 
> When enabled in a pod’s namespace, automatic injection injects the proxy configuration at pod creation time using an admission controller.

On minikube dashboard I found labels of namespaces that we are using (kubeflow, kubeflow-user-example-com) contains **istio-injection: enabled**
![image](https://user-images.githubusercontent.com/37242439/122165982-f502c780-ceb3-11eb-88f1-25ad365ffd0a.png)
Does it mean that pipeline component pods are injected sidecars by setting the labels in the pod's namespace?

**Comment by wyljpn** [comment]
Also found a YAML file related to sidecar.istio.io/inject in Kubeflow manifests, maybe it affects something? @DavidSpek 
https://github.com/kubeflow/manifests/blob/v1.3.0/common/istio-1-9-0/cluster-local-gateway/base/cluster-local-gateway.yaml#L42
https://github.com/kubeflow/manifests/blob/v1.3.0/common/istio-1-9-0/cluster-local-gateway/base/cluster-local-gateway.yaml#L54

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cluster-local-gateway
    install.operator.istio.io/owning-resource: unknown
    istio: cluster-local-gateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    release: istio
  name: cluster-local-gateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: cluster-local-gateway
      istio: cluster-local-gateway
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: '15020'
        prometheus.io/scrape: 'true'
        sidecar.istio.io/inject: 'false'
      labels:
        app: cluster-local-gateway
        chart: gateways
        heritage: Tiller
        install.operator.istio.io/owning-resource: unknown
        istio: cluster-local-gateway
        istio.io/rev: default
        operator.istio.io/component: IngressGateways
        release: istio
        service.istio.io/canonical-name: cluster-local-gateway
        service.istio.io/canonical-revision: latest
        sidecar.istio.io/inject: 'false'
...
```

**Comment by DavidSpek** [comment]
Please be aware that setting `kubectl label namespace kubeflow-user-example-com istio-injection=disabled --overwrite` will break security and user isolation (as well as some other stuff).

The user namespace has istio-injection enabled. Pods that are part of a pipeline don't have sidecars injected as they contain the `sidecar.istio.io/inject: "false"` annotation. You will most likely need to find a way for the pod created by InfraValidator component to include this annotation.

The `cluster-local-gateway` is used by KNative/KFServing and is not related to this.

@wyljpn I can't find you on Slack with the member ID, as you can only search by name. Could you send me a message so we can get in touch? You should be able to find me there quite easily.

**Comment by ConverJens** [comment]
@wyljpn It works because you are disabling the istio inject just as the annotation does. 

I think you need to understand that the pods are created by two different mechanism here: 
first pipeline pods are created through the argo workflow by KFP. All pods created this way have the `sidecar.istio.io/inject: "false"` just as I have pointed out before and as @DavidSpek iterated in his response.
second the serving pod is spawned but this pod is not created through the argo workflow but is actually created by the IV pod istself. Hence it doesn't get the needed annotation and fails because the istio webhook rejects it as it should! 

When you run `kubectl label namespace kubeflow-user-example-com istio-injection=disabled --overwrite` you manually disable all istio injects in your ns, just like the annotation does, and the pod can spawn successfully.

But as I mentioned, I have already supplied a fix for this in TFX which you can use from version 0.30.0 so this is already solved. There is nothing wrong with the KF istio policies.

Please let me know if this cleared things up for you or if you still have questions.

**Comment by wyljpn** [comment]
@DavidSpek @ConverJens Thank you for giving such detailed explanations.
I think it helped me a lot to understand how pods are created and how istio works.

I have some points that want to be checked.
 
> second the serving pod is spawned but this pod is not created through the argo workflow but is actually created by the IV pod istself. Hence it doesn't get the needed annotation and fails because the istio webhook rejects it as it should!

My understanding is that If a pod doesn't have sidecar.istio.io/inject annotation, it will not be injected Sidecar by default. And because of the istio-system's global-deny-all AuthorizationPolicy policy, the pod is not accessible. 
```
$ kubectl get AuthorizationPolicy -A
NAMESPACE                   NAME                              AGE
istio-system                cluster-local-gateway             5d10h
istio-system                global-deny-all                   5d10h
istio-system                istio-ingressgateway              5d10h
...
```
```
$ kubectl get AuthorizationPolicy global-deny-all -n istio-system -o yaml 
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"security.istio.io/v1beta1","kind":"AuthorizationPolicy","metadata":{"annotations":{},"name":"global-deny-all","namespace":"istio-system"},"spec":{}}
  creationTimestamp: "2021-06-11T14:51:22Z"
  generation: 1
  name: global-deny-all
  namespace: istio-system
  resourceVersion: "1191"
  uid: e8b243c6-23c9-48a7-8947-b297ffd7d302
spec: {}
```

That is the reason why when I set an allow-all AuthorizationPolicy, the serving pod was accessible.
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-all
  namespace: kubeflow-user-example-com
spec:
 rules:
 - {}
```

Is my understanding right?
